name: Aikido Security
on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  aikido-security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required to upload SARIF results
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect new vulnerabilities
        id: aikido-scan
        uses: AikidoSec/github-actions-workflow@v1.0.13
        with:
          secret-key: ${{ secrets.AIKIDO_SECRET_KEY }}
          fail-on-timeout: false 
          fail-on-dependency-scan: true
          fail-on-sast-scan: true
          fail-on-iac-scan: false
          minimum-severity: 'LOW'
          timeout-seconds: 180
          post-scan-status-comment: 'off'
          post-sast-review-comments: 'off'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Assuming AikidoSec/github-actions-workflow generates a SARIF file
      # If not, you need to ensure that the action does generate one.
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif